My 1st jupyter Notebook

In [1]:
import numpy as np


In [3]:
random_array=np.random.randint(0,100,size=(10,3))

In [4]:
print(random_array)

[[15 33  4]
 [41 60 31]
 [10 13  8]
 [79 78 67]
 [70  9 42]
 [48 19 88]
 [90  0 98]
 [36 78 97]
 [73 43 46]
 [83 26 68]]
